import { IProduct } from '../products/interfaces/product.interface';

export const MOCK_PRODUCTS: IProduct[] = [
  {
    id: 'p1',
    idCat: 'cat1',
    idType: 'type1',
    idTypeNew: 'typeNew1',
    productionType: 'hot-rolled',
    name: 'Труба стальная 108x4',
    manufacturer: 'Северсталь',
    steelGrade: '09Г2С',
    diameter: 108,
    gost: 'ГОСТ 8732-78',
    profileSize2: 0,
    pipeWallThickness: 4,
    status: 'active',
    koef: 1.05,
  },
  {
    id: 'p2',
    idCat: 'cat2',
    idType: 'type2',
    idTypeNew: 'typeNew2',
    productionType: 'cold-drawn',
    name: 'Труба бесшовная 57x3,5',
    manufacturer: 'ЧТПЗ',
    steelGrade: '20',
    diameter: 57,
    gost: 'ГОСТ 8734-75',
    profileSize2: 0,
    pipeWallThickness: 3.5,
    status: 'inactive',
    koef: 0.98,
  },
  {
    id: 'p3',
    idCat: 'cat1',
    idType: 'type3',
    idTypeNew: 'typeNew3',
    productionType: 'welded',
    name: 'Профильная труба 60x40x3',
    manufacturer: 'ТМК',
    steelGrade: 'Ст3',
    diameter: 60,
    gost: 'ГОСТ 30245-2003',
    profileSize2: 40,
    pipeWallThickness: 3,
    status: 'active',
    koef: 1.1,
  },
  {
    id: 'p4',
    idCat: 'cat3',
    idType: 'type4',
    idTypeNew: 'typeNew4',
    productionType: 'hot-rolled',
    name: 'Круг 45',
    manufacturer: 'Мечел',
    steelGrade: '45',
    diameter: 45,
    gost: 'ГОСТ 2590-2006',
    profileSize2: 0,
    pipeWallThickness: 0,
    status: 'active',
    koef: 1.0,
  },
  {
    id: 'p5',
    idCat: 'cat2',
    idType: 'type1',
    idTypeNew: 'typeNew5',
    productionType: 'cold-drawn',
    name: 'Труба оцинкованная 25x2',
    manufacturer: 'ОМК',
    steelGrade: '08Х18Н10',
    diameter: 25,
    gost: 'ГОСТ 3262-75',
    profileSize2: 0,
    pipeWallThickness: 2,
    status: 'archived',
    koef: 0.9,
  },
];
