import { Product } from '../products/models/product.model';

export const MOCK_PRODUCTS: Product[] = [
  // Бесшовные холоднодеформированные
  new Product({
    id: 'p1',
    idCat: 'a58d54b6-25ea-4818-afc9-1faa8c630d9a',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба бесшовная 50х3',
    manufacturer: 'Завод А',
    steelGrade: 'Ст3',
    diameter: 50,
    profileSize2: 0,
    pipeWallThickness: 3,
    status: '0',
    koef: 1,
    gost: 'GOST 8732',
  }),
  new Product({
    id: 'p2',
    idCat: 'a58d54b6-25ea-4818-afc9-1faa8c630d9a',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба бесшовная 76х4',
    manufacturer: 'Завод Б',
    steelGrade: 'Ст5',
    diameter: 50,
    profileSize2: 0,
    pipeWallThickness: 4,
    status: '0',
    koef: 1,
    gost: 'GOST 8732',
  }),
  new Product({
    id: 'p3',
    idCat: 'a58d54b6-25ea-4818-afc9-1faa8c630d9a',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба бесшовная 89х5',
    manufacturer: 'Завод В',
    steelGrade: 'Ст5',
    diameter: 89,
    profileSize2: 0,
    pipeWallThickness: 5,
    status: '0',
    koef: 1,
    gost: 'GOST 8732',
  }),
  new Product({
    id: 'p4',
    idCat: 'a58d54b6-25ea-4818-afc9-1faa8c630d9a',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба бесшовная 108х6',
    manufacturer: 'Завод Г',
    steelGrade: 'Ст20',
    diameter: 108,
    profileSize2: 0,
    pipeWallThickness: 6,
    status: '0',
    koef: 1,
    gost: 'GOST 8734',
  }),
  new Product({
    id: 'p5',
    idCat: 'a58d54b6-25ea-4818-afc9-1faa8c630d9a',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба бесшовная 133х8',
    manufacturer: 'Завод Д',
    steelGrade: 'Ст35',
    diameter: 133,
    profileSize2: 0,
    pipeWallThickness: 8,
    status: '0',
    koef: 1,
    gost: 'GOST 8732',
  }),

  // Прямошовные
  new Product({
    id: 'p6',
    idCat: 'd21de9df-f3dd-442f-8b9f-89d8f1865698',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба прямошовная 50х3',
    manufacturer: 'Завод А',
    steelGrade: 'Ст3',
    diameter: 50,
    profileSize2: 0,
    pipeWallThickness: 3,
    status: '0',
    koef: 1,
    gost: 'GOST 10704',
  }),
  new Product({
    id: 'p7',
    idCat: 'd21de9df-f3dd-442f-8b9f-89d8f1865698',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба прямошовная 76х4',
    manufacturer: 'Завод Б',
    steelGrade: 'Ст5',
    diameter: 76,
    profileSize2: 0,
    pipeWallThickness: 4,
    status: '0',
    koef: 1,
    gost: 'GOST 10705',
  }),
  new Product({
    id: 'p8',
    idCat: 'd21de9df-f3dd-442f-8b9f-89d8f1865698',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба прямошовная 89х5',
    manufacturer: 'Завод В',
    steelGrade: 'Ст10',
    diameter: 89,
    profileSize2: 0,
    pipeWallThickness: 5,
    status: '0',
    koef: 1,
    gost: 'GOST 10704',
  }),
  new Product({
    id: 'p9',
    idCat: 'd21de9df-f3dd-442f-8b9f-89d8f1865698',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба прямошовная 108х6',
    manufacturer: 'Завод Г',
    steelGrade: 'Ст20',
    diameter: 108,
    profileSize2: 0,
    pipeWallThickness: 6,
    status: '0',
    koef: 1,
    gost: 'GOST 10705',
  }),
  new Product({
    id: 'p10',
    idCat: 'd21de9df-f3dd-442f-8b9f-89d8f1865698',
    idType: 'pipe',
    idTypeNew: 'pipe_new',
    productionType: '0',
    name: 'Труба прямошовная 133х8',
    manufacturer: 'Завод Д',
    steelGrade: 'Ст35',
    diameter: 133,
    profileSize2: 0,
    pipeWallThickness: 8,
    status: '0',
    koef: 1,
    gost: 'GOST 10704',
  }),

  // Холоднокатаные
  new Product({
    id: 'p11',
    idCat: '4ae51348-d619-4bf2-a35f-1c6931b68bf1',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист холоднокатаный 1мм',
    manufacturer: 'Завод А',
    steelGrade: 'Ст08',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 19903',
  }),
  new Product({
    id: 'p12',
    idCat: '4ae51348-d619-4bf2-a35f-1c6931b68bf1',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист холоднокатаный 2мм',
    manufacturer: 'Завод Б',
    steelGrade: 'Ст08',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 19903',
  }),
  new Product({
    id: 'p13',
    idCat: '4ae51348-d619-4bf2-a35f-1c6931b68bf1',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист холоднокатаный 3мм',
    manufacturer: 'Завод В',
    steelGrade: 'Ст10',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 19904',
  }),
  new Product({
    id: 'p14',
    idCat: '4ae51348-d619-4bf2-a35f-1c6931b68bf1',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист холоднокатаный 4мм',
    manufacturer: 'Завод Г',
    steelGrade: 'Ст20',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 19903',
  }),
  new Product({
    id: 'p15',
    idCat: '4ae51348-d619-4bf2-a35f-1c6931b68bf1',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист холоднокатаный 5мм',
    manufacturer: 'Завод Д',
    steelGrade: 'Ст35',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 19905',
  }),

  // Горячекатаные
  new Product({
    id: 'p16',
    idCat: '403389a6-3f81-4cd0-bf1d-e43fe6adaa48',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист горячекатаный 2мм',
    manufacturer: 'Завод А',
    steelGrade: 'Ст08',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 16523',
  }),
  new Product({
    id: 'p17',
    idCat: '403389a6-3f81-4cd0-bf1d-e43fe6adaa48',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист горячекатаный 3мм',
    manufacturer: 'Завод Б',
    steelGrade: 'Ст10',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 16524',
  }),
  new Product({
    id: 'p18',
    idCat: '403389a6-3f81-4cd0-bf1d-e43fe6adaa48',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист горячекатаный 4мм',
    manufacturer: 'Завод В',
    steelGrade: 'Ст20',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 16525',
  }),
  new Product({
    id: 'p19',
    idCat: '403389a6-3f81-4cd0-bf1d-e43fe6adaa48',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист горячекатаный 5мм',
    manufacturer: 'Завод Г',
    steelGrade: 'Ст35',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 16526',
  }),
  new Product({
    id: 'p20',
    idCat: '403389a6-3f81-4cd0-bf1d-e43fe6adaa48',
    idType: 'sheet',
    idTypeNew: 'sheet_new',
    productionType: '0',
    name: 'Лист горячекатаный 6мм',
    manufacturer: 'Завод Д',
    steelGrade: 'Ст45',
    diameter: 0,
    profileSize2: 0,
    pipeWallThickness: 0,
    status: '0',
    koef: 1,
    gost: 'GOST 16527',
  }),
];
